### PR TITLE
Manager - Code Hygiene

### LINKED ISSUE #304: Code Hygiene - Manager
Related to #266 

### Description

This issue aims to improve the code quality of the `manager` package of `devkit`. This will help the future developments on this packages by having clean, readable and maintainable code.

The proposed solution involves the reduction of "as any" and increasing typing, validating query inputs, moving contract ABI functions to a separate library and removing ESLint since it's not used.

### TODOs

- [x] validate query inputs
- [x] reduce “as any” & increase typing
- [x] move contract ABI functions to a separate library => Including FS

### PR DESCRIPTION
**Pull request by ItsLuized**
This pull request improves the code quality of manager.

To make the code hygiene of `manager` as it was discussed in arch week n1, the following fixes were done:

- Move ABI functions to common package
- Validate Body and Query parameters with express-validator
- Remove 'as any' from 'req.body'

(There is a relative import of rpch/common because of file needed)

Closes #304

### CODE REVIEW

**Review by nionis — COMMENTED** [review]
@diegoalzate are there other areas where we can re-use these ABI functions?

**Comment by diegoalzate** [comment]
> @diegoalzate are there other areas where we can re-use these ABI functions?

i dont think so, the functions seen in the `abi.ts` can not be re used in funding service which is the other place where we interact with smart contracts.

**Review by nionis — CHANGES_REQUESTED** [review]
Please move the smart contract related code from funding service to commons too

**Review by nionis — APPROVED** [review]
LGTM
can @diegoalzate also check this to make sure moving the `hardhat` file will not cause any problems? E2E test worked so I think it's ok

**Review by diegoalzate — COMMENTED** [review]
It looks like it will work. I would rename the abi file in commons to blockchain, seems like a lot is happening in that file or maybe even split it up into abi.ts and blockchain.ts. Also I saw that the function `sendTransaction` does not receive abi through params and receives it globally, i would update those type of functions to receive the abi through params and that way it can be easier to test.

**Comment by nionis** [comment]
@diegoalzate I agree with the name change

**Comment by nionis** [comment]
@ItsLuized name change is pending here

**Pull request merged**
