### PR TITLE
Use non-root user to run executable

### LINKED ISSUE #90: secure dockerfiles
### Is your feature related to a problem?

Yes
Ensure executables in Dockerfiles are not run as root

### PR DESCRIPTION
**Pull request by ItsLuized**
Fixes #90

### CODE REVIEW

**Comment by nionis** [comment]
@ItsLuized can u resolve conflicts?
@sitilge please review once conflicts are fixed

**Review by sitilge — APPROVED** [review]
LGTM :+1:

**Review by nionis — CHANGES_REQUESTED** [review]
tests failing

**Review by nionis — APPROVED** [review]
LGTM, lets wait for @sitilge to approve too

**Review by sitilge — APPROVED** [review]

**Pull request merged**
