### PR TITLE
add paid_by column

### LINKED ISSUE #220: Tracking who used the quota and not who paid it
Update quotas table so it is visible to see who triggered the deduction of quota

### Describe the feature you'd like
It should be easy to know how many quota a trial client has used

### PR DESCRIPTION
**Pull request by diegoalzate**
fixes #220

## Overview
- adds paid_by column in quota to know who paid for the quota and now client_id is who used the quota
- added tests to make sure quota is now limited by `paid_by` attribute
- added db migrations to handle db modifications from this point onwards

### Adding quota to a client
After adding quota to 'trial' client the row would say that client_id is equal `trial` and paid_by equal to `trial`.
What is important is that when adding quota the client id and the paid by is the same, however we actually will only care who paid for it since they are the person that will actually receive the `quota` and can use it later. So if for some reason a quota is added like `client_id: 'fred', paid_by: 'bob', amount: 100` the person who can actually use the quota is bob or someone else but bob has to pay for it.

### Deducting quota from client
Again when deducting the only thing we actually will check is who paid for it, hence only the `paid_by` column matters in order to see if a client has enough quota left.

### How much quota a trial client has used
In a b2d standpoint, `client_id` will matter. It will be a the value to check how much quota a used has 'used'. I would recommend only taking into consideration amounts that are negative numbers, because if we remember that when adding a quota we have the same value in client_id and paid_by. So lets say that Sally has requested an entry node but Bob (assuming he added 100 already) is going to sponsor this request, the row would look something like this: `client_id: 'Sally', paid_by: 'Bob', amount: -10`. Meaning that now if we check who has created quotas without filtering by negative numbers it would say this:
```
sally: -1
bob: 100
```
So it is clear that sally has used an entry node but bob is only just a stat that may cause noise.

### CODE REVIEW

**Review by nionis — CHANGES_REQUESTED** [review]
- LGTM but its missing one thing, as we have running DBs now, would the dump.sql automatically transform the existing DB?

**Comment by diegoalzate** [comment]
> * LGTM but its missing one thing, as we have running DBs now, would the dump.sql automatically transform the existing DB?

Yes with this pr we would have to reset, should we add in this in pr a tool for migrations ?

**Comment by nionis** [comment]
@diegoalzate correct, lets investigate what the best practises are

**Comment by diegoalzate** [comment]
> @diegoalzate correct, lets investigate what the best practises are

added https://github.com/salsita/node-pg-migrate to run migrations from this point onward, will not support the initial dump that created all tables also the `paid_by` column is going to be nullable

**Review by nionis — APPROVED** [review]
- please write how to use or remove migrate script

**Pull request merged**
